x = int (input("Enter number : "))
y = int (input("Enter number : "))
muli=(x*y)
sum = (x+y)
divide=(x/y)
print ("The division of " +str(x) ,"by " +str(y) + " = " + str(divide))
print ("The sum of " +str(x) ,"and " +str(y) + " = " + str(sum))
print ("The muli of " +str(x) ,"and " +str(y) + " = " + str(muli))